---
title: "Stats207 Final Project Code"
output: html_document
date: "2024-06-02"
---

```{r}
data = read.csv("data.csv")
str(data)
# interested in daily changes: extracted hourly values at hour = 12
data = data[data$hour == 12, ]
# train/test split 
train = data[1:1460, ] #80%
test = data[1461:1826,] #20%
```

```{r}
# hourly pm2.5
y_train = ts(train$pm2.5) 
y_test = ts(test$pm2.5) 

# filling NAs 
# method1: forward then backward filling
# library(zoo)
# y_forward_filled = na.locf(y, na.rm = FALSE)
# y_backward_filled = na.locf(y_forward_filled, fromLast = TRUE)
# y = y_backward_filled

# method2: linear interpolation
library(forecast)
y_train = na.interp(y_train)
y_test = na.interp(y_test)

# both methods give nearly the same results
```

# ARIMA

## original data
```{r}
plot(y_train, main = "PM2.5 Concentration Though Time", ylab = "") # does not look stationary
acf(y_train, na.action = na.pass, lag.max = 100)
pacf(y_train, na.action = na.pass,lag.max = 100)
```

## first differencing
```{r}
plot(diff(y_train), main = "First Differencing of PM2.5 Concentration Though Time", ylab = "" ) # d=1, looks better 
acf(diff(y_train), na.action = na.pass, lag.max = 100, main = "ACF of First Differencing PM2.5") # q=1 or 2
pacf(diff(y_train), na.action = na.pass, lag.max = 100, main = "PACF of First Differencing PM2.5") # decays
```
non-seasonal: ACF cuts off at 2, PACF tails off
seasonal: basically nothing 

## Model fitting
```{r}
library(astsa)
```

```{r}
sarima(y_train, 0, 1, 2)
```

```{r}
sarima(y_train, 1, 1, 1)
```

```{r}
sarima(y_train, 1, 1, 2)
```
Though no obvious seasonal pattterns, try seasonal differencing
```{r}
sarima(y_train, 1, 1, 1, 1, 1, 1, 7)
```

```{r}
sarima(y_train, 1, 1, 2, 1, 1, 1, 7)
```

```{r}
sarima(y_train, 1, 1, 1, 0, 1, 1, 7)
```

## Metrics
```{r}
rmse = function(actuals, predictions) {
  return(sqrt(mean((predictions - actuals)^2)))
}
mape = function(actuals, predictions) {
  mape = mean(abs((predictions - actuals) / actuals)) * 100
  return(mape)
}
mae <- function(actuals, predictions) {
  return(mean(abs(predictions - actuals)))
}
```

## Forecasting
```{r}
m1 = Arima(y_train, order = c(0, 1, 2))
m2 = Arima(y_train, order = c(1, 1, 1))
m3 = Arima(y_train, order = c(1, 1, 2))
m4 = Arima(y_train, order = c(1, 1, 1), seasonal = list(order = c(1, 1, 1), period = 7))
m5 = Arima(y_train, order = c(1, 1, 2), seasonal = list(order = c(1, 1, 1), period = 7))
m6 = Arima(y_train, order = c(1, 1, 1), seasonal = list(order = c(0, 1, 1), period = 7))

# long-term
pred1 = forecast(m1, h = 366)$mean
tsp(pred1) = c(1, 366, 1)
pred2 = forecast(m2, h = 366)$mean
tsp(pred2) = c(1, 366, 1)
pred3 = forecast(m3, h = 366)$mean
tsp(pred3) = c(1, 366, 1)
pred4 = forecast(m4, h = 366)$mean
tsp(pred4) = c(1, 366, 1)
pred5 = forecast(m5, h = 366)$mean
tsp(pred5) = c(1, 366, 1)
pred6 = forecast(m6, h = 366)$mean
tsp(pred6) = c(1, 366, 1)

rmse(y_test, pred1)
rmse(y_test, pred2)
rmse(y_test, pred3)
rmse(y_test, pred4)
rmse(y_test, pred5)
rmse(y_test, pred6)

mae(y_test, pred1)
mae(y_test, pred2)
mae(y_test, pred3)
mae(y_test, pred4)
mae(y_test, pred5)
mae(y_test, pred6)
```

```{r}
# short-term (next week)
pred1 = forecast(m1, h = 7)$mean
tsp(pred1) = c(1, 7, 1)
pred2 = forecast(m2, h = 7)$mean
tsp(pred2) = c(1, 7, 1)
pred3 = forecast(m3, h = 7)$mean
tsp(pred3) = c(1, 7, 1)
pred4 = forecast(m4, h = 7)$mean
tsp(pred4) = c(1, 7, 1)
pred5 = forecast(m5, h = 7)$mean
tsp(pred5) = c(1, 7, 1)
pred6 = forecast(m6, h = 7)$mean
tsp(pred6) = c(1, 7, 1)

rmse(y_test[1:7], pred1)
rmse(y_test[1:7], pred2)
rmse(y_test[1:7], pred3)
rmse(y_test[1:7], pred4)
rmse(y_test[1:7], pred5)
rmse(y_test[1:7], pred6)

mae(y_test[1:7], pred1)
mae(y_test[1:7], pred2)
mae(y_test[1:7], pred3)
mae(y_test[1:7], pred4)
mae(y_test[1:7], pred5)
mae(y_test[1:7], pred6)
```

# Prophet
```{r}
# install.packages('prophet')
library(prophet)
```

```{r}
train$time = as.Date(paste(train$year, train$month, train$day, sep = "-"), "%Y-%m-%d")
df_train = data.frame(ds = train$time, y = y_train, DEWP = train$DEWP, TEMP = train$TEMP, PRES = train$PRES, Iws = train$Iws)
test$time = as.Date(paste(test$year, test$month, test$day, sep = "-"), "%Y-%m-%d")
df_test = data.frame(ds = test$time, y = y_test, DEWP = test$DEWP, TEMP = test$TEMP, PRES = test$PRES, Iws = test$Iws)
```


# long-term
```{r}
m = prophet()
m$daily.seasonality = TRUE
m$weekly.seasonality = "auto"
m$yearly.seasonality = "auto"
m$seasonality.mode = 'additive'
m$seasonality.prior.scale = 3
## add regressor
m = add_regressor(m, 'DEWP', mode = 'multiplicative') 
m = add_regressor(m, 'TEMP', mode = 'multiplicative') 
m = add_regressor(m, 'PRES', mode = 'multiplicative') 
m = add_regressor(m, 'Iws', mode = 'multiplicative') 
##
m = fit.prophet(m, df_train)

long_future = make_future_dataframe(m, periods = 366, freq = "day")
##
long_future$DEWP = data$DEWP
long_future$TEMP = data$TEMP
long_future$PRES = data$PRES
long_future$Iws = data$Iws
##
long_forecast = predict(m, long_future)
```

```{r}
rmse(y_test, long_forecast)
mae(y_test, long_forecast)
```


# short-term
```{r}
m = prophet()
m$daily.seasonality = TRUE
m$weekly.seasonality = "auto"
m$yearly.seasonality = "auto"
m$seasonality.mode = 'additive'
m$seasonality.prior.scale = 3
## add regressor
m = add_regressor(m, 'DEWP', mode = 'multiplicative')
m = add_regressor(m, 'TEMP', mode = 'multiplicative') 
m = add_regressor(m, 'PRES', mode = 'multiplicative') 
m = add_regressor(m, 'Iws', mode = 'multiplicative') 
##
m = fit.prophet(m, df_train)

short_future = make_future_dataframe(m, periods = 7, freq = "day")
##
short_future$DEWP = data[1:1467, 'DEWP']
short_future$TEMP = data[1:1467, 'TEMP']
short_future$PRES = data[1:1467, 'PRES']
short_future$Iws = data[1:1467, 'Iws']
##
short_future = predict(m, short_future)
```

# check residuals
```{r}
res = short_future[1:1460, 'yhat'] - y_train
res = res / sd(res)
plot(res, main = "Residuals of Prophet Model ")
qqnorm(res)
qqline(res, col="red") 
```

```{r}
rmse(y_test[1:7], short_future)
mae(y_test[1:7], short_future)
```

# component visualization
```{r}
prophet_plot_components(m, short_future)
```
